/**
 * Editorial seed for Back in My Days.
 * The curated "what teens actually blasted" layer, not the charts.
 * Hand-authored; hydrate.mjs resolves each {artist,title} to real
 * iTunes artwork + a 30s preview and writes src/data/capsules.json.
 *
 * @typedef {{ artist: string, title: string, hint?: string }} SeedTrack
 * @typedef {{ iso: string, countryName: string, year: number, era: string,
 *             field: "pink"|"lime"|"cyan"|"orange"|"blue", blurb: string,
 *             tracks: SeedTrack[] }} EraSeed
 */

/** @type {EraSeed[]} */
export const seeds = [
  {
    iso: "USA",
    countryName: "USA",
    year: 1990,
    era: "boombox / MTV pop-rap",
    field: "lime",
    blurb: "A boombox, a blank tape, and every cafeteria trying the Hammer dance.",
    tracks: [
      { artist: "Sinead O'Connor", title: "Nothing Compares 2 U" },
      { artist: "MC Hammer", title: "U Can't Touch This" },
      { artist: "Madonna", title: "Vogue" },
      { artist: "Bell Biv DeVoe", title: "Poison" },
      { artist: "Wilson Phillips", title: "Hold On" },
      { artist: "Vanilla Ice", title: "Ice Ice Baby" },
      { artist: "Mariah Carey", title: "Vision of Love" },
      { artist: "Roxette", title: "It Must Have Been Love" },
      { artist: "En Vogue", title: "Hold On" },
      { artist: "Depeche Mode", title: "Enjoy the Silence" },
      { artist: "Jane's Addiction", title: "Been Caught Stealing" },
      { artist: "Faith No More", title: "Epic" },
      { artist: "Janet Jackson", title: "Escapade" },
      { artist: "Billy Idol", title: "Cradle of Love" },
      { artist: "Jon Bon Jovi", title: "Blaze of Glory" },
      { artist: "Technotronic", title: "Pump Up the Jam" },
      { artist: "Paula Abdul", title: "Opposites Attract" },
      { artist: "Aerosmith", title: "Janie's Got a Gun" },
      { artist: "Phil Collins", title: "Another Day in Paradise" },
      { artist: "Snap!", title: "The Power" },
      { artist: "Digital Underground", title: "The Humpty Dance" },
      { artist: "Heart", title: "All I Wanna Do Is Make Love to You" },
      { artist: "Alannah Myles", title: "Black Velvet" },
      { artist: "Poison", title: "Unskinny Bop" },
      { artist: "Tom Petty", title: "Free Fallin'" },
      { artist: "The B-52's", title: "Love Shack" },
      { artist: "Biz Markie", title: "Just a Friend" },
      { artist: "Motley Crue", title: "Without You" },
      { artist: "New Kids On the Block", title: "Step By Step" },
      { artist: "George Michael", title: "Praying for Time" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1991,
    era: "grunge breaks / school dance",
    field: "blue",
    blurb: "The locker-door pivot: grunge on MTV, dance-pop at the gym, rap in the bus seats.",
    tracks: [
      { artist: "Nirvana", title: "Smells Like Teen Spirit" },
      { artist: "R.E.M.", title: "Losing My Religion" },
      { artist: "Bryan Adams", title: "(Everything I Do) I Do It for You" },
      { artist: "C+C Music Factory", title: "Gonna Make You Sweat (Everybody Dance Now)" },
      { artist: "EMF", title: "Unbelievable" },
      { artist: "Extreme", title: "More Than Words" },
      { artist: "Color Me Badd", title: "I Wanna Sex You Up" },
      { artist: "Metallica", title: "Enter Sandman" },
      { artist: "Red Hot Chili Peppers", title: "Give It Away" },
      { artist: "Paula Abdul", title: "Rush Rush" },
      { artist: "Boyz II Men", title: "Motownphilly" },
      { artist: "Mariah Carey", title: "Someday" },
      { artist: "Amy Grant", title: "Baby Baby" },
      { artist: "DJ Jazzy Jeff & The Fresh Prince", title: "Summertime" },
      { artist: "Divinyls", title: "I Touch Myself" },
      { artist: "Lenny Kravitz", title: "It Ain't Over 'Til It's Over" },
      { artist: "Seal", title: "Crazy" },
      { artist: "Jesus Jones", title: "Right Here, Right Now" },
      { artist: "Naughty By Nature", title: "O.P.P." },
      { artist: "Marky Mark and the Funky Bunch", title: "Good Vibrations" },
      { artist: "Madonna", title: "Justify My Love" },
      { artist: "Chris Isaak", title: "Wicked Game" },
      { artist: "Scorpions", title: "Wind of Change" },
      { artist: "Bonnie Raitt", title: "Something to Talk About" },
      { artist: "Prince", title: "Cream" },
      { artist: "George Michael", title: "Freedom! '90" },
      { artist: "Roxette", title: "Joyride" },
      { artist: "Pearl Jam", title: "Alive" },
      { artist: "Enigma", title: "Sadeness Part I" },
      { artist: "Londonbeat", title: "I've Been Thinking About You" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1992,
    era: "MTV alt / G-funk",
    field: "orange",
    blurb: "Grunge, G-funk, and big R&B choruses fighting for the same mixtape.",
    tracks: [
      { artist: "Boyz II Men", title: "End of the Road" },
      { artist: "Sir Mix-A-Lot", title: "Baby Got Back" },
      { artist: "Red Hot Chili Peppers", title: "Under the Bridge" },
      { artist: "Kris Kross", title: "Jump" },
      { artist: "Eric Clapton", title: "Tears in Heaven" },
      { artist: "TLC", title: "Baby-Baby-Baby" },
      { artist: "Guns N' Roses", title: "November Rain" },
      { artist: "Michael Jackson", title: "Black or White" },
      { artist: "En Vogue", title: "My Lovin' (You're Never Gonna Get It)" },
      { artist: "House of Pain", title: "Jump Around" },
      { artist: "Pearl Jam", title: "Jeremy" },
      { artist: "U2", title: "One" },
      { artist: "Arrested Development", title: "Tennessee" },
      { artist: "Right Said Fred", title: "I'm Too Sexy" },
      { artist: "Mr. Big", title: "To Be With You" },
      { artist: "Mariah Carey", title: "I'll Be There" },
      { artist: "The Cure", title: "Friday I'm in Love" },
      { artist: "CeCe Peniston", title: "Finally" },
      { artist: "Vanessa Williams", title: "Save the Best for Last" },
      { artist: "Billy Ray Cyrus", title: "Achy Breaky Heart" },
      { artist: "Toad the Wet Sprocket", title: "All I Want" },
      { artist: "Genesis", title: "I Can't Dance" },
      { artist: "Sophie B. Hawkins", title: "Damn I Wish I Was Your Lover" },
      { artist: "Tom Cochrane", title: "Life Is a Highway" },
      { artist: "Snap!", title: "Rhythm Is a Dancer" },
      { artist: "Shakespears Sister", title: "Stay" },
      { artist: "Alice in Chains", title: "Would?" },
      { artist: "P.M. Dawn", title: "Set Adrift on Memory Bliss" },
      { artist: "Madonna", title: "This Used to Be My Playground" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1993,
    era: "CD-store mixtape",
    field: "pink",
    blurb: "Soundtrack singles, backpack rap, and alt-rock videos after school.",
    tracks: [
      { artist: "Whitney Houston", title: "I Will Always Love You" },
      { artist: "Salt-N-Pepa", title: "Shoop" },
      { artist: "Tag Team", title: "Whoomp! (There It Is)" },
      { artist: "Janet Jackson", title: "That's the Way Love Goes" },
      { artist: "Stone Temple Pilots", title: "Plush" },
      { artist: "Blind Melon", title: "No Rain" },
      { artist: "Nirvana", title: "Heart-Shaped Box" },
      { artist: "UB40", title: "Can't Help Falling in Love" },
      { artist: "Soul Asylum", title: "Runaway Train" },
      { artist: "The Breeders", title: "Cannonball" },
      { artist: "SWV", title: "Weak" },
      { artist: "4 Non Blondes", title: "What's Up?" },
      { artist: "Spin Doctors", title: "Two Princes" },
      { artist: "Silk", title: "Freak Me" },
      { artist: "Naughty By Nature", title: "Hip Hop Hooray" },
      { artist: "Cypress Hill", title: "Insane in the Brain" },
      { artist: "Mariah Carey", title: "Dreamlover" },
      { artist: "Shai", title: "If I Ever Fall in Love" },
      { artist: "Wreckx-N-Effect", title: "Rump Shaker" },
      { artist: "Snow", title: "Informer" },
      { artist: "Duran Duran", title: "Ordinary World" },
      { artist: "Ace of Base", title: "All That She Wants" },
      { artist: "Jodeci", title: "Lately" },
      { artist: "Ice Cube", title: "It Was a Good Day" },
      { artist: "Gin Blossoms", title: "Hey Jealousy" },
      { artist: "The Cranberries", title: "Linger" },
      { artist: "The Smashing Pumpkins", title: "Today" },
      { artist: "Haddaway", title: "What Is Love" },
      { artist: "Toni Braxton", title: "Another Sad Love Song" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1994,
    era: "alt-rock takeover",
    field: "cyan",
    blurb: "Dookie, Weezer, Sabotage, and a little G-funk in the same backpack.",
    tracks: [
      { artist: "Ace of Base", title: "The Sign" },
      { artist: "All-4-One", title: "I Swear" },
      { artist: "Boyz II Men", title: "I'll Make Love to You" },
      { artist: "Celine Dion", title: "The Power of Love" },
      { artist: "Mariah Carey", title: "Hero" },
      { artist: "Lisa Loeb & Nine Stories", title: "Stay (I Missed You)" },
      { artist: "Toni Braxton", title: "Breathe Again" },
      { artist: "Salt-N-Pepa", title: "Whatta Man" },
      { artist: "Ini Kamoze", title: "Here Comes the Hotstepper" },
      { artist: "Coolio", title: "Fantastic Voyage" },
      { artist: "Aaliyah", title: "Back & Forth" },
      { artist: "Janet Jackson", title: "Again" },
      { artist: "Soundgarden", title: "Black Hole Sun" },
      { artist: "Green Day", title: "Basket Case" },
      { artist: "Beck", title: "Loser" },
      { artist: "Sheryl Crow", title: "All I Wanna Do" },
      { artist: "The Offspring", title: "Come Out and Play" },
      { artist: "Counting Crows", title: "Mr. Jones" },
      { artist: "Stone Temple Pilots", title: "Interstate Love Song" },
      { artist: "Weezer", title: "Buddy Holly" },
      { artist: "Nirvana", title: "All Apologies" },
      { artist: "The Cranberries", title: "Zombie" },
      { artist: "Collective Soul", title: "Shine" },
      { artist: "Snoop Doggy Dogg", title: "Gin and Juice" },
      { artist: "Da Brat", title: "Funkdafied" },
      { artist: "Craig Mack", title: "Flava in Ya Ear" },
      { artist: "Elton John", title: "Can You Feel the Love Tonight" },
      { artist: "Bruce Springsteen", title: "Streets of Philadelphia" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1995,
    era: "mall radio / post-grunge",
    field: "lime",
    blurb: "Friends on TV, Jagged Little Pill in the car, and every chorus enormous.",
    tracks: [
      { artist: "Coolio", title: "Gangsta's Paradise" },
      { artist: "TLC", title: "Waterfalls" },
      { artist: "TLC", title: "Creep" },
      { artist: "Seal", title: "Kiss from a Rose" },
      { artist: "Boyz II Men", title: "On Bended Knee" },
      { artist: "Real McCoy", title: "Another Night" },
      { artist: "Mariah Carey", title: "Fantasy" },
      { artist: "Madonna", title: "Take a Bow" },
      { artist: "Montell Jordan", title: "This Is How We Do It" },
      { artist: "The Notorious B.I.G.", title: "Big Poppa" },
      { artist: "Alanis Morissette", title: "Hand in My Pocket" },
      { artist: "Hootie & The Blowfish", title: "Only Wanna Be with You" },
      { artist: "Hootie & The Blowfish", title: "Let Her Cry" },
      { artist: "Blues Traveler", title: "Run-Around" },
      { artist: "Sheryl Crow", title: "Strong Enough" },
      { artist: "Bush", title: "Comedown" },
      { artist: "Silverchair", title: "Tomorrow" },
      { artist: "Better Than Ezra", title: "Good" },
      { artist: "Live", title: "Lightning Crashes" },
      { artist: "Green Day", title: "When I Come Around" },
      { artist: "The Rembrandts", title: "I'll Be There for You" },
      { artist: "Michael Jackson", title: "You Are Not Alone" },
      { artist: "Monica", title: "Don't Take It Personal (Just One of Dem Days)" },
      { artist: "Brandy", title: "Baby" },
      { artist: "2Pac", title: "Dear Mama" },
      { artist: "Luniz", title: "I Got 5 on It" },
      { artist: "Shaggy", title: "Boombastic" },
      { artist: "Bon Jovi", title: "Always" },
      { artist: "U2", title: "Hold Me, Thrill Me, Kiss Me, Kill Me" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1996,
    era: "cafeteria MTV mix",
    field: "blue",
    blurb: "Alt one-hit staples, R&B radio, and the Macarena inescapably everywhere.",
    tracks: [
      { artist: "Los Del Rio", title: "Macarena (Bayside Boys Mix)" },
      { artist: "Mariah Carey & Boyz II Men", title: "One Sweet Day" },
      { artist: "Celine Dion", title: "Because You Loved Me" },
      { artist: "Mariah Carey", title: "Always Be My Baby" },
      { artist: "Bone Thugs-N-Harmony", title: "Tha Crossroads" },
      { artist: "Toni Braxton", title: "You're Makin' Me High" },
      { artist: "2Pac", title: "California Love" },
      { artist: "Alanis Morissette", title: "Ironic" },
      { artist: "Goo Goo Dolls", title: "Name" },
      { artist: "The Smashing Pumpkins", title: "1979" },
      { artist: "Oasis", title: "Wonderwall" },
      { artist: "Fugees", title: "Killing Me Softly with His Song" },
      { artist: "No Doubt", title: "Just a Girl" },
      { artist: "BLACKstreet", title: "No Diggity" },
      { artist: "Everything But the Girl", title: "Missing (Todd Terry Remix)" },
      { artist: "Dishwalla", title: "Counting Blue Cars" },
      { artist: "Deep Blue Something", title: "Breakfast at Tiffany's" },
      { artist: "Joan Osborne", title: "One of Us" },
      { artist: "Jewel", title: "Who Will Save Your Soul" },
      { artist: "Tracy Chapman", title: "Give Me One Reason" },
      { artist: "Eric Clapton", title: "Change the World" },
      { artist: "LL Cool J", title: "Hey Lover" },
      { artist: "Busta Rhymes", title: "Woo-Hah!! Got You All in Check" },
      { artist: "Ginuwine", title: "Pony" },
      { artist: "La Bouche", title: "Be My Lover" },
      { artist: "Quad City DJ's", title: "C'mon N' Ride It (The Train)" },
      { artist: "Bush", title: "Swallowed" },
      { artist: "Sublime", title: "What I Got" },
      { artist: "Metallica", title: "Until It Sleeps" },
      { artist: "Donna Lewis", title: "I Love You Always Forever" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1997,
    era: "Spice / alt-radio",
    field: "orange",
    blurb: "Spice Girls, Hanson, alt-radio one-hit staples, and movie-single energy.",
    tracks: [
      { artist: "Elton John", title: "Candle in the Wind 1997" },
      { artist: "Jewel", title: "You Were Meant for Me" },
      { artist: "Puff Daddy & Faith Evans", title: "I'll Be Missing You" },
      { artist: "Toni Braxton", title: "Un-Break My Heart" },
      { artist: "Puff Daddy", title: "Can't Nobody Hold Me Down" },
      { artist: "R. Kelly", title: "I Believe I Can Fly" },
      { artist: "En Vogue", title: "Don't Let Go (Love)" },
      { artist: "OMC", title: "How Bizarre" },
      { artist: "Backstreet Boys", title: "Quit Playing Games (With My Heart)" },
      { artist: "Spice Girls", title: "Wannabe" },
      { artist: "Hanson", title: "MMMBop" },
      { artist: "Will Smith", title: "Men in Black" },
      { artist: "Usher", title: "You Make Me Wanna..." },
      { artist: "Third Eye Blind", title: "Semi-Charmed Life" },
      { artist: "The Notorious B.I.G.", title: "Mo Money Mo Problems" },
      { artist: "The Verve Pipe", title: "The Freshmen" },
      { artist: "The Notorious B.I.G.", title: "Hypnotize" },
      { artist: "Mariah Carey", title: "Honey" },
      { artist: "No Doubt", title: "Don't Speak" },
      { artist: "Sugar Ray", title: "Fly" },
      { artist: "Matchbox Twenty", title: "Push" },
      { artist: "Foo Fighters", title: "Everlong" },
      { artist: "Chumbawamba", title: "Tubthumping" },
      { artist: "Aqua", title: "Barbie Girl" },
      { artist: "Meredith Brooks", title: "Bitch" },
      { artist: "Sarah McLachlan", title: "Building a Mystery" },
      { artist: "Duncan Sheik", title: "Barely Breathing" },
      { artist: "Shawn Colvin", title: "Sunny Came Home" },
      { artist: "The Wallflowers", title: "One Headlight" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1998,
    era: "pre-TRL / graduation radio",
    field: "pink",
    blurb: "TRL was arriving, graduation songs were everywhere, and CDs lived in binders.",
    tracks: [
      { artist: "Next", title: "Too Close" },
      { artist: "Brandy & Monica", title: "The Boy Is Mine" },
      { artist: "Shania Twain", title: "You're Still the One" },
      { artist: "Savage Garden", title: "Truly Madly Deeply" },
      { artist: "Janet Jackson", title: "Together Again" },
      { artist: "K-Ci & JoJo", title: "All My Life" },
      { artist: "Usher", title: "Nice & Slow" },
      { artist: "Celine Dion", title: "My Heart Will Go On" },
      { artist: "Will Smith", title: "Gettin' Jiggy wit It" },
      { artist: "Goo Goo Dolls", title: "Iris" },
      { artist: "Mariah Carey", title: "My All" },
      { artist: "Monica", title: "The First Night" },
      { artist: "Destiny's Child", title: "No, No, No" },
      { artist: "Aerosmith", title: "I Don't Want to Miss a Thing" },
      { artist: "Backstreet Boys", title: "Everybody (Backstreet's Back)" },
      { artist: "Madonna", title: "Frozen" },
      { artist: "The Verve", title: "Bitter Sweet Symphony" },
      { artist: "Marcy Playground", title: "Sex and Candy" },
      { artist: "Fastball", title: "The Way" },
      { artist: "Barenaked Ladies", title: "One Week" },
      { artist: "Semisonic", title: "Closing Time" },
      { artist: "Goo Goo Dolls", title: "Slide" },
      { artist: "DMX", title: "Ruff Ryders' Anthem" },
      { artist: "Lauryn Hill", title: "Doo Wop (That Thing)" },
      { artist: "Jay-Z", title: "Hard Knock Life (Ghetto Anthem)" },
      { artist: "Jennifer Paige", title: "Crush" },
      { artist: "Third Eye Blind", title: "How's It Going to Be" },
      { artist: "Master P", title: "Make 'Em Say Uhh!" },
      { artist: "Harvey Danger", title: "Flagpole Sitta" },
      { artist: "Matchbox Twenty", title: "3AM" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1999,
    era: "peak TRL / Y2K hallway",
    field: "cyan",
    blurb: "Teen-pop saturation, nu-metal sneaking in, and Y2K hallway gossip.",
    tracks: [
      { artist: "Cher", title: "Believe" },
      { artist: "TLC", title: "No Scrubs" },
      { artist: "Monica", title: "Angel of Mine" },
      { artist: "Whitney Houston", title: "Heartbreak Hotel" },
      { artist: "Britney Spears", title: "...Baby One More Time" },
      { artist: "Sixpence None the Richer", title: "Kiss Me" },
      { artist: "Christina Aguilera", title: "Genie in a Bottle" },
      { artist: "Sugar Ray", title: "Every Morning" },
      { artist: "Ricky Martin", title: "Livin' la Vida Loca" },
      { artist: "Backstreet Boys", title: "I Want It That Way" },
      { artist: "Jennifer Lopez", title: "If You Had My Love" },
      { artist: "TLC", title: "Unpretty" },
      { artist: "Destiny's Child", title: "Bills, Bills, Bills" },
      { artist: "Smash Mouth", title: "All Star" },
      { artist: "Lou Bega", title: "Mambo No. 5 (A Little Bit of...)" },
      { artist: "LFO", title: "Summer Girls" },
      { artist: "Enrique Iglesias", title: "Bailamos" },
      { artist: "Dr. Dre", title: "Still D.R.E." },
      { artist: "Eminem", title: "My Name Is" },
      { artist: "Red Hot Chili Peppers", title: "Scar Tissue" },
      { artist: "Filter", title: "Take a Picture" },
      { artist: "blink-182", title: "What's My Age Again?" },
      { artist: "Kid Rock", title: "Bawitdaba" },
      { artist: "Limp Bizkit", title: "Nookie" },
      { artist: "Len", title: "Steal My Sunshine" },
      { artist: "Jay-Z", title: "Can I Get A..." },
      { artist: "Juvenile", title: "Back That Azz Up" },
      { artist: "Everlast", title: "What It's Like" },
      { artist: "Eagle-Eye Cherry", title: "Save Tonight" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2000,
    era: "TRL / mall-punk",
    field: "cyan",
    blurb: "TRL after school. Napster overnight. Burned CDs by morning.",
    tracks: [
      { artist: "Destiny's Child", title: "Say My Name" },
      { artist: "*NSYNC", title: "Bye Bye Bye" },
      { artist: "Britney Spears", title: "Oops!... I Did It Again" },
      { artist: "Eminem", title: "The Real Slim Shady" },
      { artist: "blink-182", title: "All the Small Things" },
      { artist: "Sisqo", title: "Thong Song" },
      { artist: "3 Doors Down", title: "Kryptonite" },
      { artist: "Madonna", title: "Music" },
      { artist: "Creed", title: "Higher" },
      { artist: "Faith Hill", title: "Breathe" },
      { artist: "Savage Garden", title: "I Knew I Loved You" },
      { artist: "Aaliyah", title: "Try Again" },
      { artist: "Nelly", title: "Country Grammar (Hot Shit)" },
      { artist: "Christina Aguilera", title: "Come On Over Baby (All I Want Is You)" },
      { artist: "Backstreet Boys", title: "Show Me the Meaning of Being Lonely" },
      { artist: "Matchbox Twenty", title: "Bent" },
      { artist: "Red Hot Chili Peppers", title: "Otherside" },
      { artist: "Jay-Z", title: "Big Pimpin'" },
      { artist: "DMX", title: "Party Up (Up in Here)" },
      { artist: "Limp Bizkit", title: "Rollin' (Air Raid Vehicle)" },
      { artist: "Papa Roach", title: "Last Resort" },
      { artist: "P!nk", title: "There You Go" },
      { artist: "Vertical Horizon", title: "Everything You Want" },
      { artist: "Santana", title: "Maria Maria" },
      { artist: "Destiny's Child", title: "Jumpin', Jumpin'" },
      { artist: "Dr. Dre", title: "The Next Episode" },
      { artist: "Macy Gray", title: "I Try" },
      { artist: "*NSYNC", title: "It's Gonna Be Me" },
      { artist: "Lonestar", title: "Amazed" },
      { artist: "Baha Men", title: "Who Let the Dogs Out" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2001,
    era: "Napster / nu-metal",
    field: "blue",
    blurb: "AIM away messages, skate videos, and a folder called mp3s.",
    tracks: [
      { artist: "Lifehouse", title: "Hanging By a Moment" },
      { artist: "Alicia Keys", title: "Fallin'" },
      { artist: "Train", title: "Drops of Jupiter (Tell Me)" },
      { artist: "Janet Jackson", title: "All for You" },
      { artist: "Linkin Park", title: "In the End" },
      { artist: "Staind", title: "It's Been Awhile" },
      { artist: "Incubus", title: "Drive" },
      { artist: "Jennifer Lopez", title: "I'm Real" },
      { artist: "Destiny's Child", title: "Survivor" },
      { artist: "Eve", title: "Let Me Blow Ya Mind" },
      { artist: "Shaggy", title: "It Wasn't Me" },
      { artist: "OutKast", title: "Ms. Jackson" },
      { artist: "Dido", title: "Thank You" },
      { artist: "Lenny Kravitz", title: "Again" },
      { artist: "Missy Elliott", title: "Get Ur Freak On" },
      { artist: "Usher", title: "U Remind Me" },
      { artist: "Nelly", title: "Ride Wit Me" },
      { artist: "Mary J. Blige", title: "Family Affair" },
      { artist: "Sum 41", title: "Fat Lip" },
      { artist: "Britney Spears", title: "I'm a Slave 4 U" },
      { artist: "Matchbox Twenty", title: "If You're Gone" },
      { artist: "Christina Aguilera", title: "Lady Marmalade" },
      { artist: "Crazy Town", title: "Butterfly" },
      { artist: "Fuel", title: "Hemorrhage (In My Hands)" },
      { artist: "Nelly Furtado", title: "I'm Like a Bird" },
      { artist: "Destiny's Child", title: "Bootylicious" },
      { artist: "U2", title: "Beautiful Day" },
      { artist: "blink-182", title: "The Rock Show" },
      { artist: "System of a Down", title: "Chop Suey!" },
      { artist: "Jay-Z", title: "Izzo (H.O.V.A.)" },
      { artist: "Michelle Branch", title: "Everywhere" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2002,
    era: "skate-punk / pop radio",
    field: "orange",
    blurb: "The CD burner was hot and every chorus was huge.",
    tracks: [
      { artist: "Nickelback", title: "How You Remind Me" },
      { artist: "Ashanti", title: "Foolish" },
      { artist: "Nelly", title: "Hot in Herre" },
      { artist: "Nelly", title: "Dilemma" },
      { artist: "The Calling", title: "Wherever You Will Go" },
      { artist: "Vanessa Carlton", title: "A Thousand Miles" },
      { artist: "Fat Joe", title: "What's Luv?" },
      { artist: "Usher", title: "U Got It Bad" },
      { artist: "Puddle of Mudd", title: "Blurry" },
      { artist: "Avril Lavigne", title: "Complicated" },
      { artist: "Ja Rule", title: "Always on Time" },
      { artist: "Jimmy Eat World", title: "The Middle" },
      { artist: "Eminem", title: "Without Me" },
      { artist: "P!nk", title: "Get the Party Started" },
      { artist: "Michelle Branch", title: "All You Wanted" },
      { artist: "Chad Kroeger", title: "Hero" },
      { artist: "Creed", title: "My Sacrifice" },
      { artist: "Shakira", title: "Whenever, Wherever" },
      { artist: "No Doubt", title: "Hey Baby" },
      { artist: "Missy Elliott", title: "Work It" },
      { artist: "Eminem", title: "Lose Yourself" },
      { artist: "Avril Lavigne", title: "Sk8er Boi" },
      { artist: "Justin Timberlake", title: "Like I Love You" },
      { artist: "Good Charlotte", title: "Lifestyles of the Rich & Famous" },
      { artist: "John Mayer", title: "No Such Thing" },
      { artist: "Kylie Minogue", title: "Can't Get You Out of My Head" },
      { artist: "Christina Aguilera", title: "Dirrty" },
      { artist: "Aaliyah", title: "Rock the Boat" },
      { artist: "Cam'ron", title: "Oh Boy" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2003,
    era: "TRL / emo starts",
    field: "pink",
    blurb: "Kazaa downloads, first eyeliner, and songs with massive bridges.",
    tracks: [
      { artist: "50 Cent", title: "In da Club" },
      { artist: "Beyonce", title: "Crazy in Love" },
      { artist: "Sean Paul", title: "Get Busy" },
      { artist: "3 Doors Down", title: "When I'm Gone" },
      { artist: "Evanescence", title: "Bring Me to Life" },
      { artist: "Matchbox Twenty", title: "Unwell" },
      { artist: "Chingy", title: "Right Thurr" },
      { artist: "Black Eyed Peas", title: "Where Is the Love?" },
      { artist: "Justin Timberlake", title: "Cry Me a River" },
      { artist: "Beyonce", title: "Baby Boy" },
      { artist: "Lil Jon & The East Side Boyz", title: "Get Low" },
      { artist: "Christina Aguilera", title: "Beautiful" },
      { artist: "Coldplay", title: "Clocks" },
      { artist: "Avril Lavigne", title: "I'm with You" },
      { artist: "Jennifer Lopez", title: "All I Have" },
      { artist: "50 Cent", title: "21 Questions" },
      { artist: "Kid Rock", title: "Picture" },
      { artist: "Jason Mraz", title: "The Remedy (I Won't Worry)" },
      { artist: "John Mayer", title: "Your Body Is a Wonderland" },
      { artist: "Audioslave", title: "Like a Stone" },
      { artist: "Jay-Z", title: "'03 Bonnie & Clyde" },
      { artist: "Kelly Clarkson", title: "Miss Independent" },
      { artist: "Pharrell", title: "Frontin'" },
      { artist: "Good Charlotte", title: "The Anthem" },
      { artist: "Trapt", title: "Headstrong" },
      { artist: "R. Kelly", title: "Ignition (Remix)" },
      { artist: "Busta Rhymes", title: "I Know What You Want" },
      { artist: "Aaliyah", title: "Miss You" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2004,
    era: "pop-punk / emo",
    field: "orange",
    blurb: "Freshman year. The CD binder was full.",
    tracks: [
      { artist: "Usher", title: "Yeah!" },
      { artist: "OutKast", title: "Hey Ya!" },
      { artist: "Maroon 5", title: "This Love" },
      { artist: "Alicia Keys", title: "If I Ain't Got You" },
      { artist: "Usher", title: "Burn" },
      { artist: "Britney Spears", title: "Toxic" },
      { artist: "Maroon 5", title: "She Will Be Loved" },
      { artist: "Linkin Park", title: "Numb" },
      { artist: "Evanescence", title: "My Immortal" },
      { artist: "Ciara", title: "Goodies" },
      { artist: "Terror Squad", title: "Lean Back" },
      { artist: "Hoobastank", title: "The Reason" },
      { artist: "Mario Winans", title: "I Don't Wanna Know" },
      { artist: "Twista", title: "Slow Jamz" },
      { artist: "Avril Lavigne", title: "My Happy Ending" },
      { artist: "blink-182", title: "I Miss You" },
      { artist: "Yellowcard", title: "Ocean Avenue" },
      { artist: "Black Eyed Peas", title: "Let's Get It Started" },
      { artist: "Kanye West", title: "Jesus Walks" },
      { artist: "Snoop Dogg", title: "Drop It Like It's Hot" },
      { artist: "Destiny's Child", title: "Lose My Breath" },
      { artist: "Modest Mouse", title: "Float On" },
      { artist: "Kelis", title: "Milkshake" },
      { artist: "The Killers", title: "Somebody Told Me" },
      { artist: "Franz Ferdinand", title: "Take Me Out" },
      { artist: "Jet", title: "Are You Gonna Be My Girl" },
      { artist: "Kelly Clarkson", title: "Breakaway" },
      { artist: "Ashlee Simpson", title: "Pieces of Me" },
      { artist: "Simple Plan", title: "Welcome to My Life" },
      { artist: "Gwen Stefani", title: "What You Waiting For?" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2005,
    era: "scene / pop-punk",
    field: "pink",
    blurb: "Homeroom, 2005. Your iPod was your whole personality.",
    tracks: [
      { artist: "Mariah Carey", title: "We Belong Together" },
      { artist: "Gwen Stefani", title: "Hollaback Girl" },
      { artist: "Mario", title: "Let Me Love You" },
      { artist: "Kelly Clarkson", title: "Since U Been Gone" },
      { artist: "Ciara", title: "1, 2 Step" },
      { artist: "Kanye West", title: "Gold Digger" },
      { artist: "The All-American Rejects", title: "Dirty Little Secret" },
      { artist: "50 Cent", title: "Candy Shop" },
      { artist: "The Pussycat Dolls", title: "Don't Cha" },
      { artist: "Kelly Clarkson", title: "Behind These Hazel Eyes" },
      { artist: "The Black Eyed Peas", title: "Don't Phunk With My Heart" },
      { artist: "Missy Elliott", title: "Lose Control" },
      { artist: "The Killers", title: "Mr. Brightside" },
      { artist: "Rihanna", title: "Pon de Replay" },
      { artist: "The Game", title: "How We Do" },
      { artist: "Weezer", title: "Beverly Hills" },
      { artist: "Fall Out Boy", title: "Sugar, We're Goin' Down" },
      { artist: "Gorillaz", title: "Feel Good Inc." },
      { artist: "Green Day", title: "Holiday" },
      { artist: "Foo Fighters", title: "Best of You" },
      { artist: "My Chemical Romance", title: "Helena" },
      { artist: "Coldplay", title: "Speed of Sound" },
      { artist: "Mariah Carey", title: "Shake It Off" },
      { artist: "The Black Eyed Peas", title: "My Humps" },
      { artist: "Nickelback", title: "Photograph" },
      { artist: "Chris Brown", title: "Run It!" },
      { artist: "Rob Thomas", title: "Lonely No More" },
      { artist: "Papa Roach", title: "Scars" },
      { artist: "Gwen Stefani", title: "Rich Girl" },
      { artist: "Will Smith", title: "Switch" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2006,
    era: "emo / scene peak",
    field: "blue",
    blurb: "The year everyone discovered eyeliner and MySpace Top 8.",
    tracks: [
      { artist: "Daniel Powter", title: "Bad Day" },
      { artist: "Sean Paul", title: "Temperature" },
      { artist: "Nelly Furtado", title: "Promiscuous" },
      { artist: "James Blunt", title: "You're Beautiful" },
      { artist: "Shakira", title: "Hips Don't Lie" },
      { artist: "Natasha Bedingfield", title: "Unwritten" },
      { artist: "Gnarls Barkley", title: "Crazy" },
      { artist: "Chamillionaire", title: "Ridin'" },
      { artist: "Justin Timberlake", title: "SexyBack" },
      { artist: "Beyonce", title: "Check on It" },
      { artist: "Mary J. Blige", title: "Be Without You" },
      { artist: "Nelly", title: "Grillz" },
      { artist: "The Fray", title: "Over My Head (Cable Car)" },
      { artist: "Cassie", title: "Me & U" },
      { artist: "The Pussycat Dolls", title: "Buttons" },
      { artist: "Ne-Yo", title: "So Sick" },
      { artist: "Rihanna", title: "SOS" },
      { artist: "Panic! at the Disco", title: "I Write Sins Not Tragedies" },
      { artist: "The All-American Rejects", title: "Move Along" },
      { artist: "Fergie", title: "London Bridge" },
      { artist: "Red Hot Chili Peppers", title: "Dani California" },
      { artist: "Snow Patrol", title: "Chasing Cars" },
      { artist: "Hinder", title: "Lips of an Angel" },
      { artist: "The Fray", title: "How to Save a Life" },
      { artist: "Fall Out Boy", title: "Dance, Dance" },
      { artist: "Cascada", title: "Everytime We Touch" },
      { artist: "AFI", title: "Miss Murder" },
      { artist: "The Killers", title: "When You Were Young" },
      { artist: "Taking Back Sunday", title: "MakeDamnSure" },
      { artist: "Evanescence", title: "Call Me When You're Sober" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2007,
    era: "scene / school-dance",
    field: "lime",
    blurb: "Senior year energy. The aux cord at every party.",
    tracks: [
      { artist: "Beyonce", title: "Irreplaceable" },
      { artist: "Rihanna", title: "Umbrella" },
      { artist: "Gwen Stefani", title: "The Sweet Escape" },
      { artist: "Fergie", title: "Big Girls Don't Cry" },
      { artist: "T-Pain", title: "Buy U a Drank (Shawty Snappin')" },
      { artist: "Plain White T's", title: "Hey There Delilah" },
      { artist: "Akon", title: "I Wanna Love You" },
      { artist: "Nelly Furtado", title: "Say It Right" },
      { artist: "Fergie", title: "Glamorous" },
      { artist: "Akon", title: "Don't Matter" },
      { artist: "Avril Lavigne", title: "Girlfriend" },
      { artist: "Rihanna", title: "Don't Stop the Music" },
      { artist: "Mims", title: "This Is Why I'm Hot" },
      { artist: "Daughtry", title: "It's Not Over" },
      { artist: "Timbaland", title: "The Way I Are" },
      { artist: "Soulja Boy Tell'em", title: "Crank That (Soulja Boy)" },
      { artist: "Justin Timberlake", title: "What Goes Around... Comes Around" },
      { artist: "Gym Class Heroes", title: "Cupid's Chokehold" },
      { artist: "Shop Boyz", title: "Party Like a Rockstar" },
      { artist: "Kanye West", title: "Stronger" },
      { artist: "Sean Kingston", title: "Beautiful Girls" },
      { artist: "Fall Out Boy", title: "This Ain't a Scene, It's an Arms Race" },
      { artist: "Linkin Park", title: "What I've Done" },
      { artist: "Colbie Caillat", title: "Bubbly" },
      { artist: "Timbaland", title: "Apologize" },
      { artist: "Amy Winehouse", title: "Rehab" },
      { artist: "Foo Fighters", title: "The Pretender" },
      { artist: "Paramore", title: "Misery Business" },
      { artist: "My Chemical Romance", title: "Welcome to the Black Parade" },
      { artist: "Alicia Keys", title: "No One" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2000,
    era: "Muz-TV / Brother 2 rock",
    field: "cyan",
    blurb: "Zemfira, Brother 2, and школьная дискотека pop on one CD-R.",
    tracks: [
      { artist: "t.A.T.u.", title: "Я сошла с ума" },
      { artist: "Zemfira", title: "Искала" },
      { artist: "Zemfira", title: "До свидания" },
      { artist: "Gosti iz Budushchego", title: "Зима в сердце" },
      { artist: "DEMO", title: "Солнышко" },
      { artist: "Bi-2", title: "Полковнику никто не пишет" },
      { artist: "Tantsy Minus", title: "Город" },
      { artist: "Mumiy Troll", title: "Карнавала.нет" },
      { artist: "Diskoteka Avariya", title: "На острие атаки" },
      { artist: "Virus!", title: "Ты меня не ищи" },
      { artist: "Hi-Fi", title: "Глупые люди" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2001,
    era: "t.A.T.u. / school disco",
    field: "blue",
    blurb: "A diary, a cassette adapter, and t.A.T.u. absolutely everywhere.",
    tracks: [
      { artist: "t.A.T.u.", title: "Я сошла с ума" },
      { artist: "t.A.T.u.", title: "Нас не догонят" },
      { artist: "DEMO", title: "Солнышко" },
      { artist: "Zemfira", title: "Трафик" },
      { artist: "Mumiy Troll", title: "Карнавала.нет" },
      { artist: "VIA Gra", title: "Я не вернусь" },
      { artist: "Gosti iz Budushchego", title: "Зима в сердце" },
      { artist: "Total", title: "Бьёт по глазам" },
      { artist: "Bi-2", title: "Серебро" },
      { artist: "Hi-Fi", title: "Глупые люди" },
      { artist: "Diskoteka Avariya", title: "На острие атаки" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2002,
    era: "Star Factory / global t.A.T.u.",
    field: "orange",
    blurb: "Star Factory on TV, t.A.T.u. going global, and everyone arguing over lyrics.",
    tracks: [
      { artist: "Zveri", title: "Дожди-пистолеты" },
      { artist: "Zemfira", title: "До свидания" },
      { artist: "Zemfira", title: "Мачо" },
      { artist: "t.A.T.u.", title: "All the Things She Said" },
      { artist: "t.A.T.u.", title: "Not Gonna Get Us" },
      { artist: "VIA Gra", title: "Я не вернусь" },
      { artist: "VIA Gra", title: "Good Morning, Papa!" },
      { artist: "Dima Bilan", title: "Я ночной хулиган" },
      { artist: "Fabrika", title: "Про любовь" },
      { artist: "Korni", title: "Ты узнаешь её" },
      { artist: "Diskoteka Avariya", title: "Небо" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2003,
    era: "Star Factory / early Zveri",
    field: "pink",
    blurb: "Early Zveri guitars, Star Factory hooks, and the first real ringtone era.",
    tracks: [
      { artist: "Diskoteka Avariya", title: "Небо" },
      { artist: "t.A.T.u.", title: "Не верь, не бойся" },
      { artist: "Zveri", title: "Дожди-пистолеты" },
      { artist: "Zveri", title: "Просто такая сильная любовь" },
      { artist: "Dima Bilan", title: "Я ночной хулиган" },
      { artist: "Gluk'oZa", title: "Швайне" },
      { artist: "Korni", title: "Ты узнаешь её" },
      { artist: "Fabrika", title: "Девушки фабричные" },
      { artist: "VIA Gra", title: "Не оставляй меня, любимый" },
      { artist: "Valeriya", title: "Часики" },
      { artist: "Gluk'oZa", title: "Невеста" },
      { artist: "Yuliya Savicheva", title: "Высоко" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2004,
    era: "pop / pop-rock",
    field: "orange",
    blurb: "Чёрный бумер on every Nokia. The двор had a soundtrack.",
    tracks: [
      { artist: "Серёга", title: "Чёрный бумер" },
      { artist: "Звери", title: "Всё, что касается" },
      { artist: "Корни", title: "Ты узнаешь её" },
      { artist: "Gluk'oZa", title: "Невеста" },
      { artist: "Фактор 2", title: "Война" },
      { artist: "Би-2", title: "Мой рок-н-ролл" },
      { artist: "Дима Билан", title: "На берегу неба" },
      { artist: "t.A.T.u.", title: "Не верь, не бойся" },
      { artist: "Splean", title: "Линия жизни" },
      { artist: "Звери", title: "Просто такая сильная любовь" },
      { artist: "Uma2rman", title: "Прасковья" },
      { artist: "Yuliya Savicheva", title: "Высоко" },
      { artist: "t.A.T.u.", title: "Нас не догонят" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2005,
    era: "pop-rock / dvor",
    field: "pink",
    blurb: "Районы, кварталы. A Walkman, a дача, and семки.",
    tracks: [
      { artist: "Звери", title: "Районы-кварталы" },
      { artist: "Земфира", title: "Прогулка" },
      { artist: "Фактор 2", title: "Красавица" },
      { artist: "Gluk'oZa", title: "Швайне" },
      { artist: "Корни", title: "Вика" },
      { artist: "t.A.T.u.", title: "Люди-инвалиды" },
      { artist: "Дима Билан", title: "Я тебя помню" },
      { artist: "Uma2rman", title: "Проститься" },
      { artist: "Жанна Фриске", title: "Ла-ла-ла" },
      { artist: "Звери", title: "Для тебя" },
      { artist: "Дискотека Авария", title: "Небо" },
      { artist: "Splean", title: "Романс" },
      { artist: "t.A.T.u.", title: "Обезьянка ноль" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2006,
    era: "Eurovision pop",
    field: "blue",
    blurb: "Билан almost won Eurovision. You knew every word.",
    tracks: [
      { artist: "Дима Билан", title: "Never Let You Go" },
      { artist: "Город 312", title: "Останусь" },
      { artist: "МакSим", title: "Трудный возраст" },
      { artist: "Дискотека Авария", title: "Малинки" },
      { artist: "BAND'EROS", title: "Манхэттен" },
      { artist: "Каста", title: "Сочиняй мечты" },
      { artist: "МакSим", title: "Ветром стать" },
      { artist: "Yuliya Savicheva", title: "Прости за любовь" },
      { artist: "Король и Шут", title: "Кукла колдуна" },
      { artist: "BAND'EROS", title: "Коламбия Пикчерз не представляет" },
      { artist: "Дискотека Авария", title: "Если хочешь остаться" },
      { artist: "Инфинити", title: "Где ты" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2007,
    era: "glam pop / school disco",
    field: "lime",
    blurb: "Серебро, МакSим, and a Motorola RAZR.",
    tracks: [
      { artist: "Серебро", title: "Song #1" },
      { artist: "МакSим", title: "Мой рай" },
      { artist: "Splean", title: "Маяк" },
      { artist: "Guf", title: "Ice Baby" },
      { artist: "Звери", title: "Дожди-пистолеты" },
      { artist: "Дима Билан", title: "Number One Fan" },
      { artist: "МакSим", title: "Отпускаю" },
      { artist: "Город 312", title: "Вне зоны доступа" },
      { artist: "Каста", title: "Вокруг шум" },
      { artist: "BAND'EROS", title: "Про красивую жизнь" },
      { artist: "Серебро", title: "Опиум" },
    ],
  },
];
