/**
 * Editorial seed for Back in My Days.
 * The curated "what teens actually blasted" layer, not the charts.
 * Hand-authored; hydrate.mjs resolves each {artist,title} to real
 * iTunes artwork + a 30s preview and writes src/data/capsules.json.
 *
 * @typedef {{ artist: string, title: string, hint?: string }} SeedTrack
 * @typedef {{ iso: string, countryName: string, year: number, era: string,
 *             field: "pink"|"lime"|"cyan"|"orange"|"blue", blurb: string,
 *             tracks: SeedTrack[] }} EraSeed
 */

/** @type {EraSeed[]} */
export const seeds = [
  {
    iso: "USA",
    countryName: "USA",
    year: 1990,
    era: "boombox / MTV pop-rap",
    field: "lime",
    blurb: "A boombox, a blank tape, and every cafeteria trying the Hammer dance.",
    tracks: [
      { artist: "MC Hammer", title: "U Can't Touch This" },
      { artist: "Vanilla Ice", title: "Ice Ice Baby" },
      { artist: "Bell Biv DeVoe", title: "Poison" },
      { artist: "Deee-Lite", title: "Groove Is in the Heart" },
      { artist: "Madonna", title: "Vogue" },
      { artist: "Wilson Phillips", title: "Hold On" },
      { artist: "New Kids On the Block", title: "Step By Step" },
      { artist: "Digital Underground", title: "The Humpty Dance" },
      { artist: "En Vogue", title: "Hold On" },
      { artist: "Jane's Addiction", title: "Been Caught Stealing" },
      { artist: "Aerosmith", title: "Janie's Got a Gun" },
      { artist: "They Might Be Giants", title: "Birdhouse in Your Soul" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1991,
    era: "grunge breaks / school dance",
    field: "blue",
    blurb: "The locker-door pivot: grunge on MTV, dance-pop at the gym, rap in the bus seats.",
    tracks: [
      { artist: "Nirvana", title: "Smells Like Teen Spirit" },
      { artist: "Pearl Jam", title: "Alive" },
      { artist: "R.E.M.", title: "Losing My Religion" },
      { artist: "Metallica", title: "Enter Sandman" },
      { artist: "Boyz II Men", title: "Motownphilly" },
      { artist: "Marky Mark and the Funky Bunch", title: "Good Vibrations" },
      { artist: "C+C Music Factory", title: "Gonna Make You Sweat (Everybody Dance Now)" },
      { artist: "Color Me Badd", title: "I Wanna Sex You Up" },
      { artist: "EMF", title: "Unbelievable" },
      { artist: "Naughty By Nature", title: "O.P.P." },
      { artist: "2Pac", title: "Brenda's Got a Baby" },
      { artist: "Michael Jackson", title: "Black or White" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1992,
    era: "MTV alt / G-funk",
    field: "orange",
    blurb: "Grunge, G-funk, and big R&B choruses fighting for the same mixtape.",
    tracks: [
      { artist: "Sir Mix-A-Lot", title: "Baby Got Back" },
      { artist: "House of Pain", title: "Jump Around" },
      { artist: "Arrested Development", title: "Tennessee" },
      { artist: "Nirvana", title: "Come As You Are" },
      { artist: "Red Hot Chili Peppers", title: "Under the Bridge" },
      { artist: "The Black Crowes", title: "Remedy" },
      { artist: "TLC", title: "Ain't 2 Proud 2 Beg" },
      { artist: "Boyz II Men", title: "End of the Road" },
      { artist: "En Vogue", title: "My Lovin' (You're Never Gonna Get It)" },
      { artist: "Kris Kross", title: "Jump" },
      { artist: "The Lemonheads", title: "It's a Shame About Ray" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1993,
    era: "CD-store mixtape",
    field: "pink",
    blurb: "Soundtrack singles, backpack rap, and alt-rock videos after school.",
    tracks: [
      { artist: "Snoop Dogg", title: "Gin and Juice" },
      { artist: "Wu-Tang Clan", title: "C.R.E.A.M." },
      { artist: "The Smashing Pumpkins", title: "Today" },
      { artist: "Pearl Jam", title: "Daughter" },
      { artist: "Nirvana", title: "Heart-Shaped Box" },
      { artist: "Cypress Hill", title: "Insane in the Brain" },
      { artist: "A Tribe Called Quest", title: "Award Tour" },
      { artist: "Counting Crows", title: "Mr. Jones" },
      { artist: "The Breeders", title: "Cannonball" },
      { artist: "Tag Team", title: "Whoomp! (There It Is)" },
      { artist: "4 Non Blondes", title: "What's Up?" },
      { artist: "Mariah Carey", title: "Dreamlover" },
      { artist: "The Cranberries", title: "Linger" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1994,
    era: "alt-rock takeover",
    field: "cyan",
    blurb: "Dookie, Weezer, Sabotage, and a little G-funk in the same backpack.",
    tracks: [
      { artist: "Green Day", title: "Basket Case" },
      { artist: "Weezer", title: "Buddy Holly" },
      { artist: "The Offspring", title: "Come Out and Play" },
      { artist: "Beastie Boys", title: "Sabotage" },
      { artist: "Beck", title: "Loser" },
      { artist: "Soundgarden", title: "Black Hole Sun" },
      { artist: "Nine Inch Nails", title: "Closer" },
      { artist: "TLC", title: "Creep" },
      { artist: "Aaliyah", title: "Back & Forth" },
      { artist: "The Notorious B.I.G.", title: "Juicy" },
      { artist: "Lisa Loeb & Nine Stories", title: "Stay (I Missed You)" },
      { artist: "Ace of Base", title: "The Sign" },
      { artist: "Coolio", title: "Fantastic Voyage" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1995,
    era: "mall radio / post-grunge",
    field: "lime",
    blurb: "Friends on TV, Jagged Little Pill in the car, and every chorus enormous.",
    tracks: [
      { artist: "Coolio", title: "Gangsta's Paradise" },
      { artist: "TLC", title: "Waterfalls" },
      { artist: "No Doubt", title: "Just a Girl" },
      { artist: "Montell Jordan", title: "This Is How We Do It" },
      { artist: "Luniz", title: "I Got 5 On It" },
      { artist: "Mariah Carey", title: "Fantasy" },
      { artist: "The Rembrandts", title: "I'll Be There for You" },
      { artist: "Goo Goo Dolls", title: "Name" },
      { artist: "Blues Traveler", title: "Run-Around" },
      { artist: "Collective Soul", title: "December" },
      { artist: "Seal", title: "Kiss from a Rose" },
      { artist: "Bone Thugs-N-Harmony", title: "1st of tha Month" },
      { artist: "Oasis", title: "Wonderwall" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1996,
    era: "cafeteria MTV mix",
    field: "blue",
    blurb: "Alt one-hit staples, R&B radio, and the Macarena inescapably everywhere.",
    tracks: [
      { artist: "No Doubt", title: "Don't Speak" },
      { artist: "2Pac", title: "California Love" },
      { artist: "Fugees", title: "Killing Me Softly With His Song" },
      { artist: "Blackstreet", title: "No Diggity" },
      { artist: "Sublime", title: "What I Got" },
      { artist: "Beck", title: "Where It's At" },
      { artist: "The Smashing Pumpkins", title: "1979" },
      { artist: "Alanis Morissette", title: "Ironic" },
      { artist: "Jewel", title: "Who Will Save Your Soul" },
      { artist: "Butthole Surfers", title: "Pepper" },
      { artist: "Primitive Radio Gods", title: "Standing Outside a Broken Phone Booth with Money in My Hand" },
      { artist: "Donna Lewis", title: "I Love You Always Forever" },
      { artist: "Quad City DJ's", title: "C'mon N' Ride It (The Train)" },
      { artist: "Los Del Rio", title: "Macarena" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1997,
    era: "Spice / alt-radio",
    field: "orange",
    blurb: "Spice Girls, Hanson, alt-radio one-hit staples, and movie-single energy.",
    tracks: [
      { artist: "Spice Girls", title: "Wannabe" },
      { artist: "Hanson", title: "MMMBop" },
      { artist: "Third Eye Blind", title: "Semi-Charmed Life" },
      { artist: "Sugar Ray", title: "Fly" },
      { artist: "Aqua", title: "Barbie Girl" },
      { artist: "Backstreet Boys", title: "Quit Playing Games (With My Heart)" },
      { artist: "Meredith Brooks", title: "Bitch" },
      { artist: "The Verve Pipe", title: "The Freshmen" },
      { artist: "Smash Mouth", title: "Walkin' On the Sun" },
      { artist: "Foo Fighters", title: "Everlong" },
      { artist: "The Notorious B.I.G.", title: "Hypnotize" },
      { artist: "Will Smith", title: "Men In Black" },
      { artist: "Marcy Playground", title: "Sex and Candy" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1998,
    era: "pre-TRL / graduation radio",
    field: "pink",
    blurb: "TRL was arriving, graduation songs were everywhere, and CDs lived in binders.",
    tracks: [
      { artist: "Britney Spears", title: "...Baby One More Time" },
      { artist: "*NSYNC", title: "I Want You Back" },
      { artist: "Backstreet Boys", title: "Everybody (Backstreet's Back)" },
      { artist: "Brandy & Monica", title: "The Boy Is Mine" },
      { artist: "Goo Goo Dolls", title: "Iris" },
      { artist: "Semisonic", title: "Closing Time" },
      { artist: "Barenaked Ladies", title: "One Week" },
      { artist: "Eve 6", title: "Inside Out" },
      { artist: "Harvey Danger", title: "Flagpole Sitta" },
      { artist: "Beastie Boys", title: "Intergalactic" },
      { artist: "Lauryn Hill", title: "Doo Wop (That Thing)" },
      { artist: "Jay-Z", title: "Hard Knock Life (Ghetto Anthem)" },
      { artist: "DMX", title: "Ruff Ryders' Anthem" },
      { artist: "Fatboy Slim", title: "The Rockafeller Skank" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 1999,
    era: "peak TRL / Y2K hallway",
    field: "cyan",
    blurb: "Teen-pop saturation, nu-metal sneaking in, and Y2K hallway gossip.",
    tracks: [
      { artist: "Backstreet Boys", title: "I Want It That Way" },
      { artist: "Christina Aguilera", title: "Genie In a Bottle" },
      { artist: "TLC", title: "No Scrubs" },
      { artist: "Destiny's Child", title: "Bills, Bills, Bills" },
      { artist: "Eminem", title: "My Name Is" },
      { artist: "blink-182", title: "What's My Age Again?" },
      { artist: "Limp Bizkit", title: "Nookie" },
      { artist: "Korn", title: "Freak On a Leash" },
      { artist: "Smash Mouth", title: "All Star" },
      { artist: "Len", title: "Steal My Sunshine" },
      { artist: "Sugar Ray", title: "Every Morning" },
      { artist: "Red Hot Chili Peppers", title: "Scar Tissue" },
      { artist: "Lou Bega", title: "Mambo No. 5 (A Little Bit Of...)" },
      { artist: "Sixpence None the Richer", title: "Kiss Me" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2000,
    era: "TRL / mall-punk",
    field: "cyan",
    blurb: "TRL after school. Napster overnight. Burned CDs by morning.",
    tracks: [
      { artist: "blink-182", title: "All the Small Things" },
      { artist: "Limp Bizkit", title: "Rollin' (Air Raid Vehicle)" },
      { artist: "Linkin Park", title: "One Step Closer" },
      { artist: "Papa Roach", title: "Last Resort" },
      { artist: "Eminem", title: "The Real Slim Shady" },
      { artist: "Britney Spears", title: "Oops!... I Did It Again" },
      { artist: "*NSYNC", title: "Bye Bye Bye" },
      { artist: "Destiny's Child", title: "Say My Name" },
      { artist: "3 Doors Down", title: "Kryptonite" },
      { artist: "Red Hot Chili Peppers", title: "Californication" },
      { artist: "Nine Days", title: "Absolutely (Story of a Girl)" },
      { artist: "Vertical Horizon", title: "Everything You Want" },
      { artist: "Eve 6", title: "Promise" },
      { artist: "Wheatus", title: "Teenage Dirtbag" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2001,
    era: "Napster / nu-metal",
    field: "blue",
    blurb: "AIM away messages, skate videos, and a folder called mp3s.",
    tracks: [
      { artist: "Linkin Park", title: "In the End" },
      { artist: "Sum 41", title: "Fat Lip" },
      { artist: "Alien Ant Farm", title: "Smooth Criminal" },
      { artist: "Jimmy Eat World", title: "The Middle" },
      { artist: "Weezer", title: "Hash Pipe" },
      { artist: "Staind", title: "It's Been Awhile" },
      { artist: "System of a Down", title: "Chop Suey!" },
      { artist: "Incubus", title: "Drive" },
      { artist: "Eve 6", title: "Here's to the Night" },
      { artist: "Michelle Branch", title: "Everywhere" },
      { artist: "Alicia Keys", title: "Fallin'" },
      { artist: "Missy Elliott", title: "Get Ur Freak On" },
      { artist: "Gorillaz", title: "Clint Eastwood" },
      { artist: "The Strokes", title: "Last Nite" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2002,
    era: "skate-punk / pop radio",
    field: "orange",
    blurb: "The CD burner was hot and every chorus was huge.",
    tracks: [
      { artist: "Avril Lavigne", title: "Sk8er Boi" },
      { artist: "Good Charlotte", title: "Lifestyles of the Rich & Famous" },
      { artist: "Simple Plan", title: "I'd Do Anything" },
      { artist: "New Found Glory", title: "My Friends Over You" },
      { artist: "Puddle of Mudd", title: "Blurry" },
      { artist: "The White Stripes", title: "Fell In Love With a Girl" },
      { artist: "No Doubt", title: "Hella Good" },
      { artist: "Nelly", title: "Hot In Herre" },
      { artist: "Eminem", title: "Lose Yourself" },
      { artist: "Vanessa Carlton", title: "A Thousand Miles" },
      { artist: "Michelle Branch", title: "All You Wanted" },
      { artist: "Hoobastank", title: "Running Away" },
      { artist: "Unwritten Law", title: "Seein' Red" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2003,
    era: "TRL / emo starts",
    field: "pink",
    blurb: "Kazaa downloads, first eyeliner, and songs with massive bridges.",
    tracks: [
      { artist: "Evanescence", title: "Bring Me To Life" },
      { artist: "The All-American Rejects", title: "Swing, Swing" },
      { artist: "Simple Plan", title: "Perfect" },
      { artist: "Yellowcard", title: "Ocean Avenue" },
      { artist: "Good Charlotte", title: "The Anthem" },
      { artist: "Linkin Park", title: "Numb" },
      { artist: "OutKast", title: "Hey Ya!" },
      { artist: "Beyoncé", title: "Crazy In Love" },
      { artist: "50 Cent", title: "In da Club" },
      { artist: "Fountains of Wayne", title: "Stacy's Mom" },
      { artist: "The Ataris", title: "The Boys of Summer" },
      { artist: "AFI", title: "Girl's Not Grey" },
      { artist: "Story of the Year", title: "Until the Day I Die" },
      { artist: "Trapt", title: "Headstrong" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2004,
    era: "pop-punk / emo",
    field: "orange",
    blurb: "Freshman year. The CD binder was full.",
    tracks: [
      { artist: "Green Day", title: "Wake Me Up When September Ends" },
      { artist: "Yellowcard", title: "Ocean Avenue" },
      { artist: "blink-182", title: "I Miss You" },
      { artist: "Sum 41", title: "Pieces" },
      { artist: "My Chemical Romance", title: "I'm Not Okay (I Promise)" },
      { artist: "Modest Mouse", title: "Float On" },
      { artist: "Taking Back Sunday", title: "A Decade Under the Influence" },
      { artist: "New Found Glory", title: "All Downhill from Here" },
      { artist: "Bowling for Soup", title: "1985" },
      { artist: "Hawthorne Heights", title: "Ohio Is for Lovers" },
      { artist: "The Killers", title: "Mr. Brightside" },
      { artist: "Switchfoot", title: "Dare You to Move" },
      { artist: "Story of the Year", title: "Until the Day I Die" },
      { artist: "Jimmy Eat World", title: "Pain" },
      { artist: "Good Charlotte", title: "Predictable" },
      { artist: "Avril Lavigne", title: "My Happy Ending" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2005,
    era: "scene / pop-punk",
    field: "pink",
    blurb: "Homeroom, 2005. Your iPod was your whole personality.",
    tracks: [
      { artist: "The All-American Rejects", title: "Dirty Little Secret" },
      { artist: "Fall Out Boy", title: "Sugar, We're Goin Down" },
      { artist: "My Chemical Romance", title: "Helena" },
      { artist: "Green Day", title: "Holiday" },
      { artist: "Simple Plan", title: "Welcome to My Life" },
      { artist: "Kelly Clarkson", title: "Since U Been Gone" },
      { artist: "Gorillaz", title: "Feel Good Inc." },
      { artist: "Weezer", title: "Beverly Hills" },
      { artist: "Death Cab for Cutie", title: "Soul Meets Body" },
      { artist: "Foo Fighters", title: "Best of You" },
      { artist: "Gwen Stefani", title: "Hollaback Girl" },
      { artist: "Motion City Soundtrack", title: "Everything Is Alright" },
      { artist: "Relient K", title: "Be My Escape" },
      { artist: "Rise Against", title: "Swing Life Away" },
      { artist: "The Academy Is...", title: "Slow Down" },
      { artist: "System of a Down", title: "Chop Suey!" },
      { artist: "Coldplay", title: "Speed of Sound" },
      { artist: "Avenged Sevenfold", title: "Bat Country" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2006,
    era: "emo / scene peak",
    field: "blue",
    blurb: "The year everyone discovered eyeliner and MySpace Top 8.",
    tracks: [
      { artist: "Panic! at the Disco", title: "I Write Sins Not Tragedies" },
      { artist: "Fall Out Boy", title: "Dance, Dance" },
      { artist: "The All-American Rejects", title: "Move Along" },
      { artist: "AFI", title: "Miss Murder" },
      { artist: "My Chemical Romance", title: "Welcome to the Black Parade" },
      { artist: "The Killers", title: "When You Were Young" },
      { artist: "Red Hot Chili Peppers", title: "Dani California" },
      { artist: "Snow Patrol", title: "Chasing Cars" },
      { artist: "Hellogoodbye", title: "Here (In Your Arms)" },
      { artist: "OK Go", title: "Here It Goes Again" },
      { artist: "Taking Back Sunday", title: "MakeDamnSure" },
      { artist: "Angels & Airwaves", title: "The Adventure" },
      { artist: "Saosin", title: "Voices" },
      { artist: "Hinder", title: "Lips of an Angel" },
      { artist: "Yellowcard", title: "Lights and Sounds" },
      { artist: "Rise Against", title: "Ready to Fall" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2007,
    era: "scene / school-dance",
    field: "lime",
    blurb: "Senior year energy. The aux cord at every party.",
    tracks: [
      { artist: "Plain White T's", title: "Hey There Delilah" },
      { artist: "Paramore", title: "Misery Business" },
      { artist: "Boys Like Girls", title: "The Great Escape" },
      { artist: "Gym Class Heroes", title: "Cupid's Chokehold" },
      { artist: "Fall Out Boy", title: "Thnks fr th Mmrs" },
      { artist: "Avril Lavigne", title: "Girlfriend" },
      { artist: "Linkin Park", title: "What I've Done" },
      { artist: "OneRepublic", title: "Apologize" },
      { artist: "Timbaland", title: "The Way I Are" },
      { artist: "Rihanna", title: "Umbrella" },
      { artist: "Soulja Boy", title: "Crank That (Soulja Boy)" },
      { artist: "Cute Is What We Aim For", title: "Curse of Curves" },
      { artist: "Foo Fighters", title: "The Pretender" },
      { artist: "Jimmy Eat World", title: "Big Casino" },
      { artist: "Cartel", title: "Honestly" },
      { artist: "Good Charlotte", title: "Keep Your Hands Off My Girl" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2000,
    era: "Muz-TV / Brother 2 rock",
    field: "cyan",
    blurb: "Zemfira, Brother 2, and школьная дискотека pop on one CD-R.",
    tracks: [
      { artist: "t.A.T.u.", title: "Я сошла с ума" },
      { artist: "Zemfira", title: "Искала" },
      { artist: "Zemfira", title: "До свидания" },
      { artist: "Gosti iz Budushchego", title: "Зима в сердце" },
      { artist: "DEMO", title: "Солнышко" },
      { artist: "Bi-2", title: "Полковнику никто не пишет" },
      { artist: "Tantsy Minus", title: "Город" },
      { artist: "Mumiy Troll", title: "Карнавала.нет" },
      { artist: "Diskoteka Avariya", title: "На острие атаки" },
      { artist: "Virus!", title: "Ты меня не ищи" },
      { artist: "Hi-Fi", title: "Глупые люди" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2001,
    era: "t.A.T.u. / school disco",
    field: "blue",
    blurb: "A diary, a cassette adapter, and t.A.T.u. absolutely everywhere.",
    tracks: [
      { artist: "t.A.T.u.", title: "Я сошла с ума" },
      { artist: "t.A.T.u.", title: "Нас не догонят" },
      { artist: "DEMO", title: "Солнышко" },
      { artist: "Zemfira", title: "Трафик" },
      { artist: "Mumiy Troll", title: "Карнавала.нет" },
      { artist: "VIA Gra", title: "Я не вернусь" },
      { artist: "Gosti iz Budushchego", title: "Зима в сердце" },
      { artist: "Total", title: "Бьёт по глазам" },
      { artist: "Bi-2", title: "Серебро" },
      { artist: "Hi-Fi", title: "Глупые люди" },
      { artist: "Diskoteka Avariya", title: "На острие атаки" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2002,
    era: "Star Factory / global t.A.T.u.",
    field: "orange",
    blurb: "Star Factory on TV, t.A.T.u. going global, and everyone arguing over lyrics.",
    tracks: [
      { artist: "Zveri", title: "Дожди-пистолеты" },
      { artist: "Zemfira", title: "До свидания" },
      { artist: "Zemfira", title: "Мачо" },
      { artist: "t.A.T.u.", title: "All the Things She Said" },
      { artist: "t.A.T.u.", title: "Not Gonna Get Us" },
      { artist: "VIA Gra", title: "Я не вернусь" },
      { artist: "VIA Gra", title: "Good Morning, Papa!" },
      { artist: "Dima Bilan", title: "Я ночной хулиган" },
      { artist: "Fabrika", title: "Про любовь" },
      { artist: "Korni", title: "Ты узнаешь её" },
      { artist: "Diskoteka Avariya", title: "Небо" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2003,
    era: "Star Factory / early Zveri",
    field: "pink",
    blurb: "Early Zveri guitars, Star Factory hooks, and the first real ringtone era.",
    tracks: [
      { artist: "Diskoteka Avariya", title: "Небо" },
      { artist: "t.A.T.u.", title: "Не верь, не бойся" },
      { artist: "Zveri", title: "Дожди-пистолеты" },
      { artist: "Zveri", title: "Просто такая сильная любовь" },
      { artist: "Dima Bilan", title: "Я ночной хулиган" },
      { artist: "Gluk'oZa", title: "Швайне" },
      { artist: "Korni", title: "Ты узнаешь её" },
      { artist: "Fabrika", title: "Девушки фабричные" },
      { artist: "VIA Gra", title: "Не оставляй меня, любимый" },
      { artist: "Valeriya", title: "Часики" },
      { artist: "Gluk'oZa", title: "Невеста" },
      { artist: "Yuliya Savicheva", title: "Высоко" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2004,
    era: "pop / pop-rock",
    field: "orange",
    blurb: "Чёрный бумер on every Nokia. The двор had a soundtrack.",
    tracks: [
      { artist: "Серёга", title: "Чёрный бумер" },
      { artist: "Звери", title: "Всё, что касается" },
      { artist: "Корни", title: "Ты узнаешь её" },
      { artist: "Gluk'oZa", title: "Невеста" },
      { artist: "Фактор 2", title: "Война" },
      { artist: "Би-2", title: "Мой рок-н-ролл" },
      { artist: "Дима Билан", title: "На берегу неба" },
      { artist: "t.A.T.u.", title: "Не верь, не бойся" },
      { artist: "Splean", title: "Линия жизни" },
      { artist: "Звери", title: "Просто такая сильная любовь" },
      { artist: "Uma2rman", title: "Прасковья" },
      { artist: "Yuliya Savicheva", title: "Высоко" },
      { artist: "t.A.T.u.", title: "Нас не догонят" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2005,
    era: "pop-rock / dvor",
    field: "pink",
    blurb: "Районы, кварталы. A Walkman, a дача, and семки.",
    tracks: [
      { artist: "Звери", title: "Районы-кварталы" },
      { artist: "Земфира", title: "Прогулка" },
      { artist: "Фактор 2", title: "Красавица" },
      { artist: "Gluk'oZa", title: "Швайне" },
      { artist: "Корни", title: "Вика" },
      { artist: "t.A.T.u.", title: "Люди-инвалиды" },
      { artist: "Дима Билан", title: "Я тебя помню" },
      { artist: "Uma2rman", title: "Проститься" },
      { artist: "Жанна Фриске", title: "Ла-ла-ла" },
      { artist: "Звери", title: "Для тебя" },
      { artist: "Дискотека Авария", title: "Небо" },
      { artist: "Splean", title: "Романс" },
      { artist: "t.A.T.u.", title: "Обезьянка ноль" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2006,
    era: "Eurovision pop",
    field: "blue",
    blurb: "Билан almost won Eurovision. You knew every word.",
    tracks: [
      { artist: "Дима Билан", title: "Never Let You Go" },
      { artist: "Город 312", title: "Останусь" },
      { artist: "МакSим", title: "Трудный возраст" },
      { artist: "Дискотека Авария", title: "Малинки" },
      { artist: "BAND'EROS", title: "Манхэттен" },
      { artist: "Каста", title: "Сочиняй мечты" },
      { artist: "МакSим", title: "Ветром стать" },
      { artist: "Yuliya Savicheva", title: "Прости за любовь" },
      { artist: "Король и Шут", title: "Кукла колдуна" },
      { artist: "BAND'EROS", title: "Коламбия Пикчерз не представляет" },
      { artist: "Дискотека Авария", title: "Если хочешь остаться" },
      { artist: "Инфинити", title: "Где ты" },
    ],
  },
  {
    iso: "RUS",
    countryName: "Russia",
    year: 2007,
    era: "glam pop / school disco",
    field: "lime",
    blurb: "Серебро, МакSим, and a Motorola RAZR.",
    tracks: [
      { artist: "Серебро", title: "Song #1" },
      { artist: "МакSим", title: "Мой рай" },
      { artist: "Splean", title: "Маяк" },
      { artist: "Guf", title: "Ice Baby" },
      { artist: "Звери", title: "Дожди-пистолеты" },
      { artist: "Дима Билан", title: "Number One Fan" },
      { artist: "МакSим", title: "Отпускаю" },
      { artist: "Город 312", title: "Вне зоны доступа" },
      { artist: "Каста", title: "Вокруг шум" },
      { artist: "BAND'EROS", title: "Про красивую жизнь" },
      { artist: "Серебро", title: "Опиум" },
    ],
  },
];
