/**
 * Editorial seed for Back in My Days.
 * The curated "what teens actually blasted" layer, not the charts.
 * Hand-authored; hydrate.mjs resolves each {artist,title} to real
 * iTunes artwork + a 30s preview and writes src/data/capsules.json.
 *
 * @typedef {{ artist: string, title: string, hint?: string }} SeedTrack
 * @typedef {{ iso: string, countryName: string, year: number, era: string,
 *             field: "pink"|"lime"|"cyan"|"orange"|"blue", blurb: string,
 *             tracks: SeedTrack[] }} EraSeed
 */

/** @type {EraSeed[]} */
export const seeds = [
  {
    iso: "USA",
    countryName: "USA",
    year: 2004,
    era: "pop-punk / emo",
    field: "orange",
    blurb: "Freshman year. The CD binder was full.",
    tracks: [
      { artist: "Green Day", title: "Wake Me Up When September Ends" },
      { artist: "Yellowcard", title: "Ocean Avenue" },
      { artist: "blink-182", title: "I Miss You" },
      { artist: "Sum 41", title: "Pieces" },
      { artist: "My Chemical Romance", title: "I'm Not Okay (I Promise)" },
      { artist: "Modest Mouse", title: "Float On" },
      { artist: "Taking Back Sunday", title: "A Decade Under the Influence" },
      { artist: "New Found Glory", title: "All Downhill from Here" },
      { artist: "Bowling for Soup", title: "1985" },
      { artist: "Hawthorne Heights", title: "Ohio Is for Lovers" },
      { artist: "The Killers", title: "Mr. Brightside" },
      { artist: "Switchfoot", title: "Dare You to Move" },
      { artist: "Story of the Year", title: "Until the Day I Die" },
      { artist: "Jimmy Eat World", title: "Pain" },
      { artist: "Good Charlotte", title: "Predictable" },
      { artist: "Avril Lavigne", title: "My Happy Ending" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2005,
    era: "scene / pop-punk",
    field: "pink",
    blurb: "Homeroom, 2005. Your iPod was your whole personality.",
    tracks: [
      { artist: "The All-American Rejects", title: "Dirty Little Secret" },
      { artist: "Fall Out Boy", title: "Sugar, We're Goin Down" },
      { artist: "My Chemical Romance", title: "Helena" },
      { artist: "Green Day", title: "Holiday" },
      { artist: "Simple Plan", title: "Welcome to My Life" },
      { artist: "Kelly Clarkson", title: "Since U Been Gone" },
      { artist: "Gorillaz", title: "Feel Good Inc." },
      { artist: "Weezer", title: "Beverly Hills" },
      { artist: "Death Cab for Cutie", title: "Soul Meets Body" },
      { artist: "Foo Fighters", title: "Best of You" },
      { artist: "Gwen Stefani", title: "Hollaback Girl" },
      { artist: "Motion City Soundtrack", title: "Everything Is Alright" },
      { artist: "Relient K", title: "Be My Escape" },
      { artist: "Rise Against", title: "Swing Life Away" },
      { artist: "The Academy Is...", title: "Slow Down" },
      { artist: "System of a Down", title: "Chop Suey!" },
      { artist: "Coldplay", title: "Speed of Sound" },
      { artist: "Avenged Sevenfold", title: "Bat Country" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2006,
    era: "emo / scene peak",
    field: "blue",
    blurb: "The year everyone discovered eyeliner and MySpace Top 8.",
    tracks: [
      { artist: "Panic! at the Disco", title: "I Write Sins Not Tragedies" },
      { artist: "Fall Out Boy", title: "Dance, Dance" },
      { artist: "The All-American Rejects", title: "Move Along" },
      { artist: "AFI", title: "Miss Murder" },
      { artist: "My Chemical Romance", title: "Welcome to the Black Parade" },
      { artist: "The Killers", title: "When You Were Young" },
      { artist: "Red Hot Chili Peppers", title: "Dani California" },
      { artist: "Snow Patrol", title: "Chasing Cars" },
      { artist: "Hellogoodbye", title: "Here (In Your Arms)" },
      { artist: "OK Go", title: "Here It Goes Again" },
      { artist: "Taking Back Sunday", title: "MakeDamnSure" },
      { artist: "Angels & Airwaves", title: "The Adventure" },
      { artist: "Saosin", title: "Voices" },
      { artist: "Hinder", title: "Lips of an Angel" },
      { artist: "Yellowcard", title: "Lights and Sounds" },
      { artist: "Rise Against", title: "Ready to Fall" },
    ],
  },
  {
    iso: "USA",
    countryName: "USA",
    year: 2007,
    era: "scene / school-dance",
    field: "lime",
    blurb: "Senior year energy. The aux cord at every party.",
    tracks: [
      { artist: "Plain White T's", title: "Hey There Delilah" },
      { artist: "Paramore", title: "Misery Business" },
      { artist: "Boys Like Girls", title: "The Great Escape" },
      { artist: "Gym Class Heroes", title: "Cupid's Chokehold" },
      { artist: "Fall Out Boy", title: "Thnks fr th Mmrs" },
      { artist: "Avril Lavigne", title: "Girlfriend" },
      { artist: "Linkin Park", title: "What I've Done" },
      { artist: "OneRepublic", title: "Apologize" },
      { artist: "Timbaland", title: "The Way I Are" },
      { artist: "Rihanna", title: "Umbrella" },
      { artist: "Soulja Boy", title: "Crank That (Soulja Boy)" },
      { artist: "Cute Is What We Aim For", title: "Curse of Curves" },
      { artist: "Foo Fighters", title: "The Pretender" },
      { artist: "Jimmy Eat World", title: "Big Casino" },
      { artist: "Cartel", title: "Honestly" },
      { artist: "Good Charlotte", title: "Keep Your Hands Off My Girl" },
    ],
  },
];
